insert into category (id, country, code) values (1, 'Germany', 'DE');
insert into category (id, country, code) values (2, 'United States', 'US');
insert into category (id, country, code) values (3, 'Poland', 'PL');

insert into medication (name, producer, refundation, category_id) values ('Diazepam', 'TYA Pharmaceuticals', 0.21, 1);
insert into medication (name, producer, refundation, category_id) values ('Prozac', 'Dista Products Company', 0.96, 2);
insert into medication (name, producer, refundation, category_id) values ('ETHAMBUTOL HYDROCHLORIDE', 'REMEDYREPACK INC.', 0.0, 3);
insert into medication (name, producer, refundation, category_id) values ('TYLENOL COLD', 'McNeil Consumer Healthcare Div McNeil-PPC, Inc', 0.62, 1);
insert into medication (name, producer, refundation, category_id) values ('MULTI ACTION POWER', 'AMI Cosmetic Co.,Ltd.', 0.98, 2);
insert into medication (name, producer, refundation, category_id) values ('VANIQA', 'Physicians Total Care, Inc.', 0.9, 2);
insert into medication (name, producer, refundation, category_id) values ('XtraCare Anti-Dandruff Hair Cleanse', 'Rejoice International Inc.', 0.54, 1);
insert into medication (name, producer, refundation, category_id) values ('alcohol', 'Sion Biotext Medical Ltd', 0.11, 1);
insert into medication (name, producer, refundation, category_id) values ('Vitamin K1', 'Hospira, Inc.', 0.48, 3);
insert into medication (name, producer, refundation, category_id) values ('Bio Chem Detox', 'BioActive Nutritional, Inc.', 0.72, 1);
insert into medication (name, producer, refundation, category_id) values ('Acetazolamide', 'REMEDYREPACK INC.', 0.82, 1);
insert into medication (name, producer, refundation, category_id) values ('Hydroxyzine Hydrochloride', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', 0.72, 2);
insert into medication (name, producer, refundation, category_id) values ('Pollens - Weeds, Dock/Sorrel Mix', 'Jubilant HollisterStier LLC', 0.73, 3);
insert into medication (name, producer, refundation, category_id) values ('Clear Choice Ibuprofen', 'Athlete''s Needs Inc', 0.81, 3);
insert into medication (name, producer, refundation, category_id) values ('Nortriptyline Hydrochloride', 'Watson Laboratories, Inc.', 0.06, 1);
insert into medication (name, producer, refundation, category_id) values ('OXYCODONE AND ACETAMINOPHEN', 'Physicians Total Care, Inc.', 0.54, 1);
insert into medication (name, producer, refundation, category_id) values ('Xylocaine', 'Dentsply Pharmaceutical', 0.75, 1);
insert into medication (name, producer, refundation, category_id) values ('Mentholatum Pain Relief Deep Heating', 'The Mentholatum Company', 0.1, 3);
insert into medication (name, producer, refundation, category_id) values ('Ferrum sidereum Sulfur', 'Uriel Pharmacy Inc.', 0.35, 2);
insert into medication (name, producer, refundation, category_id) values ('Androbalance', 'BioActive Nutritional, Inc.', 0.74, 2);
insert into medication (name, producer, refundation, category_id) values ('Bupropion Hydrochloride', 'Actavis South Atlantic LLC', 0.19, 2);
insert into medication (name, producer, refundation, category_id) values ('REN Satin Perfection BB Sunscreen Broad Spectrum SPF 15 Light-Medium', 'Ren Ltd.', 0.61, 1);
insert into medication (name, producer, refundation, category_id) values ('Bupropion Hydrochloride', 'Global Pharmaceuticals, Division of Impax Laboratories, Inc.', 0.8, 3);
insert into medication (name, producer, refundation, category_id) values ('acyclovir', 'Zydus Pharmaceuticals (USA) Inc.', 0.36, 3);
insert into medication (name, producer, refundation, category_id) values ('TechneScan HDP', 'Mallinckrodt Inc.', 0.48, 3);
insert into medication (name, producer, refundation, category_id) values ('Strattera', 'Physicians Total Care, Inc.', 0.9, 3);
insert into medication (name, producer, refundation, category_id) values ('Miconazole 7', 'Equate', 0.67, 3);
insert into medication (name, producer, refundation, category_id) values ('Childrens Ibuprofen', 'Walgreen Company', 0.94, 2);
insert into medication (name, producer, refundation, category_id) values ('Quetiapine Fumarate', 'Teva Pharmaceuticals USA Inc', 0.09, 1);
insert into medication (name, producer, refundation, category_id) values ('Synalar', 'Medimetriks Pharmaceuticals, Inc.', 0.4, 2);
insert into medication (name, producer, refundation, category_id) values ('Chlorhexidine Gluconate', 'LLC Federal Solutions', 0.1, 3);
insert into medication (name, producer, refundation, category_id) values ('equate pain and fever', 'Wal-Mart Stores Inc', 0.72, 1);
insert into medication (name, producer, refundation, category_id) values ('PRINIVIL', 'Merck Sharp & Dohme Corp.', 0.15, 2);
insert into medication (name, producer, refundation, category_id) values ('Alendronate Sodium', 'Watson Laboratories, Inc.', 0.61, 3);
insert into medication (name, producer, refundation, category_id) values ('Antibacterial Hand', 'Family Dollar Services Inc', 0.8, 3);
insert into medication (name, producer, refundation, category_id) values ('Lidocaine Hydrochloride', 'General Injectables & Vaccines, Inc', 0.83, 1);
insert into medication (name, producer, refundation, category_id) values ('Instant hand Sanitizer', 'Target Corp.', 0.74, 3);
insert into medication (name, producer, refundation, category_id) values ('Buttermilk Time Frame Future Resist Foundation Broad Spectrum SPF 20', 'Delilah Cosmetics', 0.19, 2);
insert into medication (name, producer, refundation, category_id) values ('Zanaflex', 'Acorda Therapeutics, Inc.', 0.55, 3);
insert into medication (name, producer, refundation, category_id) values ('Tramadol Hydrchloride', 'REMEDYREPACK INC.', 0.81, 2);
insert into medication (name, producer, refundation, category_id) values ('Soothe', 'Bausch & Lomb Incorporated', 0.56, 3);
insert into medication (name, producer, refundation, category_id) values ('Wal itin D', 'Walgreen Company', 0.91, 3);
insert into medication (name, producer, refundation, category_id) values ('Zidovudine', 'REMEDYREPACK INC.', 0.46, 3);
insert into medication (name, producer, refundation, category_id) values ('Protonix', 'Wyeth Pharmaceuticals Inc., a subsidiary of Pfizer Inc.', 0.74, 1);
insert into medication (name, producer, refundation, category_id) values ('CENTER-AL - CARYA ILLINOINENSIS POLLEN', 'ALK-Abello, Inc.', 0.08, 3);
insert into medication (name, producer, refundation, category_id) values ('POTASSIUM CHLORIDE', 'DIRECT RX', 0.58, 3);
insert into medication (name, producer, refundation, category_id) values ('Grama Grass', 'Nelco Laboratories, Inc.', 0.33, 1);
insert into medication (name, producer, refundation, category_id) values ('White Birch', 'Nelco Laboratories, Inc.', 0.38, 1);
insert into medication (name, producer, refundation, category_id) values ('Mometasone Furoate', 'Harris Pharmaceutical, Inc.', 0.01, 2);
insert into medication (name, producer, refundation, category_id) values ('topiramate', 'American Health Packaging', 0.31, 3);